services:
  mysql:
    image: mysql:8.0
    container_name: drone-platform-mysql
    ports:
      - "${MYSQL_PORT}:3306"
    env_file:
      - .env
    volumes:
      - drone_mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: drone-platform-redis
    ports:
      - "${REDIS_PORT}:6379"
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}

  app:
    build: .
    container_name: drone-platform-app
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - mysql
      - redis
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod

volumes:
  drone_mysql_data: