name: Docker Build CI

on:
  push:
    branches: [ "dev", "feat/*" ]
  pull_request:
    branches: [ "dev", "main"]

jobs:
  docker-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # 최신 v4 사용 권장

      - name: Setup config files
        run: |
          cp src/main/resources/application_sample.yaml src/main/resources/application.yaml
          cp compose_sample.yaml compose.yaml

      - name: Generate .env file
        run: |
          touch .env
          echo "APP_PORT=${{ secrets.APP_PORT }}" >> .env
          echo "DOCKER_IMAGE_NAME=${{ secrets.DOCKER_IMAGE_NAME }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "S3_SERVER_ROLE=${{ secrets.S3_SERVER_ROLE }}" >> .env
          echo "S3_SERVER_REGION=${{ secrets.S3_SERVER_REGION }}" >> .env
          echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}" >> .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "MYSQL_PORT=${{ secrets.MYSQL_PORT }}" >> .env
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> .env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Run with Compose
        run: |
          docker compose up -d --build

      - name: Check container status
        run: |
          sleep 20 # 컨테이너 초기화 시간 확보
          docker ps
          # 앱 컨테이너가 정상 실행 중인지 확인하는 로직 추가 가능
          if [ $(docker inspect -f '{{.State.Running}}' drone-platform-app) != "true" ]; then
            echo "App container failed to start"
            exit 1
          fi

      - name: Stop containers
        if: always()
        run: docker compose down